"""add_preferences_and_unique_constraint

Revision ID: 7199fc93f001
Revises: a3f1b2c4d5e6
Create Date: 2026-06-10 06:18:06.006122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7199fc93f001'
down_revision: Union[str, None] = 'a3f1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_emails_account_message', 'emails', ['mail_account_id', 'message_id'])
    op.add_column('mail_accounts', sa.Column('notify_telegram', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('mail_accounts', sa.Column('deliver_to_dashboard', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('mail_accounts', sa.Column('forward_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_accounts', 'forward_enabled')
    op.drop_column('mail_accounts', 'deliver_to_dashboard')
    op.drop_column('mail_accounts', 'notify_telegram')
    op.drop_constraint('uq_emails_account_message', 'emails', type_='unique')
    # ### end Alembic commands ###
