"""add_forwarding_rules_table

Revision ID: 97613a2857f6
Revises: 7199fc93f001
Create Date: 2026-06-10 06:20:46.329933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97613a2857f6'
down_revision: Union[str, None] = '7199fc93f001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarding_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mail_account_id', sa.UUID(), nullable=True),
    sa.Column('condition_subject_contains', sa.Text(), nullable=True),
    sa.Column('condition_from_domain', sa.Text(), nullable=True),
    sa.Column('condition_from_email', sa.Text(), nullable=True),
    sa.Column('condition_body_contains', sa.Text(), nullable=True),
    sa.Column('forward_to_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarding_rules_mail_account_id'), 'forwarding_rules', ['mail_account_id'], unique=False)
    op.create_index(op.f('ix_forwarding_rules_user_id'), 'forwarding_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarding_rules_user_id'), table_name='forwarding_rules')
    op.drop_index(op.f('ix_forwarding_rules_mail_account_id'), table_name='forwarding_rules')
    op.drop_table('forwarding_rules')
    # ### end Alembic commands ###
