"""add_notification_limit_per_hour

Revision ID: e0a0ad9a1987
Revises: 97613a2857f6
Create Date: 2026-06-10 23:03:34.989651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a0ad9a1987'
down_revision: Union[str, None] = '97613a2857f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with server_default so existing rows aren't rejected by NOT NULL constraint
    op.add_column(
        'users',
        sa.Column(
            'notification_limit_per_hour',
            sa.Integer(),
            nullable=False,
            server_default='20',
        )
    )
    # Remove the server default after backfill so future inserts use Python-side default
    op.alter_column('users', 'notification_limit_per_hour', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_limit_per_hour')
    # ### end Alembic commands ###
